name: Build and test UPM packages for platforms on all available Unity Versions

on:
  pull_request:
    branches-ignore:    
      - 'release'
  # Ignore PRs targetting main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  # Run Unity multi-version build unit tests defined in the package
  Run-Unit-Tests:
    name: Run Unity Unit Tests
    uses: ./.github/workflows/rununitybuildmultiversion.yml

  # Update the package release version
  #Update-Version:
  #  name: Update Package Version
  #  uses: ./.github/workflows/tagrelease.yml
  #  with:
  #    build-target: windows
  #  secrets: inherit      